# Generated by Django 5.1.3 on 2025-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='ocupacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(default='Simples', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='preco_por_noite',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
