# Generated by Django 5.1.5 on 2025-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hospede_cidade_hospede_ocupacao_quarto_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
